name: Spread secrets to all repositories

on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  github-secret-spreader:
    name: Spread secrets
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Set public key
        run: |
          sed -i -e 's/{{public-key}}/'${{ secrets.SPREAD_PUBLIC_KEY }}'/' spreaded-secrets.yml
      - name: Update secrets
        shell: bash
        run: |
          echo -n ${{ secrets.PGP_PASSPHRASE }} | bin/encrypt > PGP_PASSPHRASE
          echo -n ${{ secrets.PGP_SECRET }} | bin/encrypt > PGP_SECRET
          echo -n ${{ secrets.SONATYPE_PASSWORD }} | bin/encrypt > SONATYPE_PASSWORD
          echo -n ${{ secrets.SONATYPE_USERNAME }} | bin/encrypt > SONATYPE_USERNAME
          echo -n ${{ secrets.ADMIN_GITHUB_TOKEN }} | bin/encrypt > ADMIN_GITHUB_TOKEN
          echo -n ${{ secrets.REQUIRES_JEKYLL_CI }} | bin/encrypt > REQUIRES_JEKYLL_CI
          echo -n ${{ secrets.REQUIRES_PUBLISH_MICROSITE }} | bin/encrypt > REQUIRES_PUBLISH_MICROSITE
          echo -n ${{ secrets.REQUIRES_CODECOV }} | bin/encrypt > REQUIRES_CODECOV
      - name: Spread secrets
        run: bin/spread
        env:
          SPREAD_GITHUB_TOKEN: ${{ secrets.SPREAD_GITHUB_TOKEN }}
          SPREAD_PRIVATE_KEY: ${{ secrets.SPREAD_PRIVATE_KEY }}
